# Generated by Django 3.2.13 on 2022-06-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_booking_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='cost',
            field=models.IntegerField(null=True),
        ),
    ]
