# Generated by Django 3.2.13 on 2022-06-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20220626_2310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='id',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_no',
            field=models.CharField(default='313CE', editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
